CREATE TABLE connection_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    database_type VARCHAR(32) NOT NULL,
    auth_type VARCHAR(32) NOT NULL,
    host VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL,
    database_name VARCHAR(255),
    service_name VARCHAR(255),
    schema_name VARCHAR(255),
    username VARCHAR(255),
    jdbc_parameters VARCHAR(2048),
    trust_store_path VARCHAR(255),
    key_store_path VARCHAR(255),
    tls_enabled BOOLEAN NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_connection_profile_name UNIQUE (name)
);

CREATE TABLE migration_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    source_profile_id BIGINT NOT NULL,
    target_profile_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL,
    source_schema VARCHAR(255),
    selected_objects_json VARCHAR(10000),
    entire_schema BOOLEAN NOT NULL,
    overwrite BOOLEAN NOT NULL,
    current_phase VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE,
    started_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    output_directory VARCHAR(255),
    completed_units INTEGER NOT NULL,
    failed_units INTEGER NOT NULL,
    CONSTRAINT fk_job_source_profile FOREIGN KEY (source_profile_id) REFERENCES connection_profile(id),
    CONSTRAINT fk_job_target_profile FOREIGN KEY (target_profile_id) REFERENCES connection_profile(id)
);

CREATE TABLE job_checkpoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    phase VARCHAR(255),
    object_type VARCHAR(255),
    object_name VARCHAR(255),
    chunk_number INTEGER NOT NULL,
    status VARCHAR(40),
    error_message VARCHAR(4000),
    retry_count INTEGER NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_checkpoint_job FOREIGN KEY (job_id) REFERENCES migration_job(id),
    CONSTRAINT uk_checkpoint_unit UNIQUE (job_id, phase, object_type, object_name, chunk_number)
);

CREATE TABLE audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT,
    action VARCHAR(255),
    detail VARCHAR(2000),
    occurred_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_migration_job_status ON migration_job(status);
CREATE INDEX idx_checkpoint_job_status ON job_checkpoint(job_id, status);
CREATE INDEX idx_audit_event_job ON audit_event(job_id, occurred_at);
