CREATE TABLE logical_table (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    auto_compare BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_logical_table_name UNIQUE (name)
);

CREATE TABLE logical_column (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logical_table_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    excluded BOOLEAN NOT NULL DEFAULT FALSE,
    primary_key_position INTEGER,
    CONSTRAINT fk_logical_column_table FOREIGN KEY (logical_table_id) REFERENCES logical_table(id),
    CONSTRAINT uk_logical_column_name UNIQUE (logical_table_id, name)
);

CREATE TABLE db_table_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logical_table_id BIGINT NOT NULL,
    connection_profile_id BIGINT NOT NULL,
    schema_name VARCHAR(255) NOT NULL,
    table_name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_db_mapping_logical FOREIGN KEY (logical_table_id) REFERENCES logical_table(id),
    CONSTRAINT fk_db_mapping_profile FOREIGN KEY (connection_profile_id) REFERENCES connection_profile(id),
    CONSTRAINT uk_db_table_mapping UNIQUE (connection_profile_id, schema_name, table_name)
);

CREATE TABLE recon_db_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logical_table_id BIGINT NOT NULL,
    source_table_mapping_id BIGINT NOT NULL,
    target_table_mapping_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_recon_logical FOREIGN KEY (logical_table_id) REFERENCES logical_table(id),
    CONSTRAINT fk_recon_source FOREIGN KEY (source_table_mapping_id) REFERENCES db_table_mapping(id),
    CONSTRAINT fk_recon_target FOREIGN KEY (target_table_mapping_id) REFERENCES db_table_mapping(id),
    CONSTRAINT uk_recon_table_pair UNIQUE (source_table_mapping_id, target_table_mapping_id)
);

CREATE TABLE recon_column_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recon_db_mapping_id BIGINT NOT NULL,
    logical_column_id BIGINT NOT NULL,
    source_column_name VARCHAR(255) NOT NULL,
    target_column_name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_column_mapping_recon FOREIGN KEY (recon_db_mapping_id) REFERENCES recon_db_mapping(id),
    CONSTRAINT fk_column_mapping_logical FOREIGN KEY (logical_column_id) REFERENCES logical_column(id),
    CONSTRAINT uk_recon_logical_column UNIQUE (recon_db_mapping_id, logical_column_id),
    CONSTRAINT uk_recon_source_column UNIQUE (recon_db_mapping_id, source_column_name),
    CONSTRAINT uk_recon_target_column UNIQUE (recon_db_mapping_id, target_column_name)
);

CREATE TABLE recon_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_recon_batch_name UNIQUE (name)
);

CREATE TABLE recon_batch_table (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    recon_db_mapping_id BIGINT NOT NULL,
    execution_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_batch_table_batch FOREIGN KEY (batch_id) REFERENCES recon_batch(id),
    CONSTRAINT fk_batch_table_recon FOREIGN KEY (recon_db_mapping_id) REFERENCES recon_db_mapping(id),
    CONSTRAINT uk_batch_table UNIQUE (batch_id, recon_db_mapping_id)
);

CREATE INDEX idx_logical_column_table ON logical_column(logical_table_id);
CREATE INDEX idx_db_mapping_logical ON db_table_mapping(logical_table_id);
CREATE INDEX idx_recon_mapping_logical ON recon_db_mapping(logical_table_id);
CREATE INDEX idx_batch_table_batch ON recon_batch_table(batch_id, execution_order);
